easy_admin:
  entities:
    #        # List the entity class name you want to manage
    Category:
      class: App\Entity\Category
      image_base_path: '%uploads_url_categories%'
      list:
        fields:
          - 'Label'
          - { property: 'picture', type: 'image' }
      form:
        fields:
          - 'label'
          - { property: 'picture', type: 'file_upload', type_options: { upload_dir: '%uploads_directory_cities%', download_path: '%uploads_url_cities%' } }
      edit:
        fields:
          - 'id'
    City:
      class: App\Entity\City
      image_base_path: '%uploads_url_cities%'

      list:
        fields:
          - 'Label'
          - { property: 'picture', type: 'image' }

      form:
        fields:
          - 'label'
          - { property: 'picture', type: 'file_upload', type_options: { upload_dir: '%uploads_directory_cities%', download_path: '%uploads_url_cities%' } }
          - 'name'
          - 'lat'
          - 'lng'

      edit:
        fields:
          - 'id'
          - { property: 'picture', type: 'file_upload', type_options: { upload_dir: '%uploads_directory_cities%', download_path: '%uploads_url_cities%' } }


    User:
      class: App\Entity\User
      list:
        actions: ['-new', '-edit']
        fields:
          - 'lastname'
          - 'firstname'
          - "Email"
      form:
        fields:
          - 'firstname'
          - 'lastname'
      edit:
        fields:
          - 'lastname'
          - 'firstname'
          - "Email"
    Activity:
      class: App\Entity\Activity
      list:
        actions: ['-new', '-edit']
        fields:
          - 'title'
      form:
        fields:
          - 'title'
          - 'address'
          - 'eventdate'
          - 'description'
          - 'user'
          - 'city'
          - 'category'
    Comment:
      class: App\Entity\Comment
      list:
        actions: ['-new', '-edit']
        fields:
          - 'title'
          - 'content'
        form:
          fields:
            - 'title'
            - 'content'
