easy_admin:
  formats:
    date: 'd/m/Y'
    datetime: 'd/m/Y H:i'
  entities:
    #        # List the entity class name you want to manage
    Category:
      class: App\Entity\Category
      list:
        fields:
          - 'Label'
          - { property: 'picture', type: 'image', base_path: '%uploads_url_categories%' }
      form:
        fields:
          - 'label'
          - { property: 'pictureFile', type: 'vich_image' }

      edit:
        fields:
          - 'label'
          - { property: 'pictureFile', type: 'vich_image' }
    City:
      class: App\Entity\City
      list:
        fields:
          - 'Label'
          - { property: 'picture', type: 'image', base_path: '%uploads_url_cities%' }
      form:
        fields:
          - 'label'
          - { property: 'pictureFile', type: 'vich_image' }
          - { property: 'headerphotoFile', type: 'vich_image' }
          - 'name'
          - 'lat'
          - 'lng'


      edit:
        fields:
          - 'id'
          - { property: 'pictureFile', type: 'vich_image' }
          - { property: 'headerphotoFile', type: 'vich_image' }
          - 'name'
          - 'lat'
          - 'lng'



    User:
      class: App\Entity\User
      list:
        actions: ['-new', '-edit']
        fields:
          - 'lastname'
          - 'firstname'
          - "Email"
          - 'dateofbirth'
      form:
        fields:
          - 'firstname'
          - 'lastname'
      edit:
        fields:
          - 'lastname'
          - 'firstname'
          - "Email"
    Activity:
      class: App\Entity\Activity
      list:
        actions: ['-new', '-edit']
        fields:
          - 'title'
          - 'eventdate'
          - 'createdAt'
      form:
        fields:
          - 'title'
          - 'address'
          - 'eventdate'
          - 'description'
          - 'user'
          - 'city'
          - 'category'
    Comment:
      class: App\Entity\Comment
      list:
        actions: ['-new']
        fields:
          - 'content'
          - 'activity'

        form:
          fields:
            - 'content'
            - 'activity'
        edit:
          fields:
            - 'content'


