App\Entity\User:
  properties:
    firstname:
      - Length:
          min: 2
          max: 30
          minMessage: 'Votre prénom doit contenir plus de {{ limit }} caractères'
          maxMessage: 'Votre prénom ne peut pas être plus long que {{ limit }} caractères'
          allowEmptyString: false
    lastname:
      - Length:
          min: 2
          max: 30
          minMessage: 'Votre nom doit contenir plus de {{ limit }} caractères'
          maxMessage: 'Votre nom ne peut pas être plus long que {{ limit }} caractères'
          allowEmptyString: false

App\Entity\Activity:
  properties:
    title:
      - Length:
          min: 2
          max: 50
          minMessage: 'Votre titre doit contenir plus de {{ limit }} caractères'
          maxMessage: 'Votre titre ne peut pas être plus long que {{ limit }} caractères'
          allowEmptyString: false
    description:
      - Length:
          min: 2
          max: 400
          minMessage: 'Votre description doit contenir plus de {{ limit }} caractères'
          maxMessage: 'Votre description ne peut pas être plus longue que {{ limit }} caractères'
          allowEmptyString: false
    address:
      - Length:
          min: 2
          max: 100
          minMessage: 'Votre adresse doit contenir plus de {{ limit }} caractères'
          maxMessage: 'Votre adresse ne peut pas être plus longue que {{ limit }} caractères'
          allowEmptyString: false
