App\Entity\User:
  properties:
    firstname:
      - Length:
          min: 2
          max: 30
          minMessage: 'Votre prénom doit contenir plus de {{ limit }} caractères'
          maxMessage: 'Votre prénom ne peut pas être plus long que {{ limit }} caractères'
    lastname:
      - Length:
          min: 2
          max: 30
          minMessage: 'Votre nom doit contenir plus de {{ limit }} caractères'
          maxMessage: 'Votre nom ne peut pas être plus long que {{ limit }} caractères'
    dateofbirth:
      - LessThan:
          value: -50 years
          message: "Vous devez avoir au moins 50 ans pour accéder à Solitude accompagnée"

App\Entity\Activity:
  properties:
    title:
      - Length:
          min: 2
          max: 50
          minMessage: 'Votre titre doit contenir plus de {{ limit }} caractères'
          maxMessage: 'Votre titre ne peut pas être plus long que {{ limit }} caractères'
    description:
      - Length:
          min: 2
          max: 400
          minMessage: 'Votre description doit contenir plus de {{ limit }} caractères'
          maxMessage: 'Votre description ne peut pas être plus longue que {{ limit }} caractères'
    address:
      - Length:
          min: 2
          max: 100
          minMessage: 'Votre adresse doit contenir plus de {{ limit }} caractères'
          maxMessage: 'Votre adresse ne peut pas être plus longue que {{ limit }} caractères'
    eventdate:
        - GreaterThan:
            value: today
            message: "La date de l'activité ne doit pas être dans le passé "
App\Entity\Comment:
  properties:
    content:
      - Length:
          min: 1
          max: 300
          minMessage: 'Votre commentaire doit contenir plus de {{ limit }} caractères'
          maxMessage: 'Votre commentaire ne peut pas être plus long que {{ limit }} caractères'
